# Generated by Django 2.2.2 on 2019-06-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultflex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='plan_name',
            field=models.CharField(default='fixds', max_length=20),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='tenor_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='littledrops',
            name='custom_name',
            field=models.CharField(default='littledrops', max_length=20),
        ),
        migrations.AddField(
            model_name='littledrops',
            name='plan_name',
            field=models.CharField(default='littledrops', max_length=20),
        ),
        migrations.AddField(
            model_name='rentplus',
            name='custom_name',
            field=models.CharField(default='rentplus', max_length=20),
        ),
        migrations.AddField(
            model_name='rentplus',
            name='plan_name',
            field=models.CharField(default='rentplus', max_length=20),
        ),
        migrations.AddField(
            model_name='rentplus',
            name='tenor_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetsaving',
            name='plan_name',
            field=models.CharField(default='targetsavings', max_length=20),
        ),
        migrations.AddField(
            model_name='targetsaving',
            name='tenor_ended',
            field=models.BooleanField(default=False),
        ),
    ]
