# Generated by Django 2.2.2 on 2019-06-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultflex', '0002_auto_20190623_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='littledrops',
            name='last_drop_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
