# Generated by Django 2.2.2 on 2019-06-08 21:26

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.CharField(max_length=30)),
                ('loan_period', models.CharField(choices=[('30', '30 DAYS'), ('15', '15 DAYS')], max_length=30)),
                ('interest_rate', models.CharField(max_length=30)),
                ('repayment_amount', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('running', 'RUNNING'), ('settled', 'SETTLED'), ('default', 'DEFAULT')], max_length=10)),
                ('start_date', models.DateTimeField(blank=True)),
                ('due_date', models.DateTimeField(blank=True)),
                ('repayment_even', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applications',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicantsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='phone_number')),
                ('bank_name', models.CharField(blank=True, choices=[('044', 'Access Bank'), ('063', 'Access Bank Diamond'), ('050', 'Ecobank'), ('070', 'Fidelity Bank'), ('011', 'First Bank'), ('214', 'FCMB'), ('058', 'GTB'), ('030', 'Heritage Bank'), ('082', 'Keystone'), ('076', 'Polaris (Skye Bank)'), ('221', 'Stanbic IBTC'), ('232', 'Sterling Bank'), ('032', 'Union Bank'), ('215', 'Unity Bank'), ('035', 'Wema Bank'), ('057', 'Zenith Bank')], max_length=30)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
