# Generated by Django 2.2.2 on 2019-06-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicantsProfile',
        ),
    ]
