# Generated by Django 2.2.2 on 2019-06-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_delete_applicantsprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('running', 'RUNNING'), ('settled', 'SETTLED'), ('default', 'DEFAULT'), ('failed', 'FAILED')], max_length=10),
        ),
    ]
