# Generated by Django 2.2.2 on 2019-06-13 21:00

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acctmang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'EMPLOYED'), ('selfEmployed', 'SELF-EMPLOYED'), ('retired', 'RETIRED'), ('unemployed', 'UNEMPLOYED'), ('student', 'STUDENT')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='income_range',
            field=models.CharField(blank=True, choices=[('below31k', 'BELOW ₦31,000'), ('31-50k', 'BETWEEN ₦31,000 & ₦50,000'), ('50-80k', 'BETWEEN ₦50,000 & ₦80,000'), ('80-100k', 'BETWEEN ₦80,000 & ₦100K'), ('100-150k', 'BETWEEN ₦100K & ₦150K'), ('250-500k', 'BETWEEN ₦250K & 500K'), ('500-1m', 'BETWEEN ₦500K & 1M'), ('above1m', 'ABOVE 1M')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('single', 'SINGLE'), ('married', 'MARRIED')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=' ', editable=False, populate_from='phone_number'),
            preserve_default=False,
        ),
    ]
